# Generated by Django 3.2.1 on 2021-06-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0006_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_products',
            field=models.IntegerField(default=0),
        ),
    ]
