# Generated by Django 3.2.1 on 2021-06-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0007_order_total_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
