# Generated by Django 3.2.1 on 2021-06-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0004_auto_20210603_1500'),
        ('my_admin', '0004_auto_20210604_2316'),
        ('my_admin', '0008_order_note'),
    ]

    operations = [
    ]
