# Generated by Django 3.2.1 on 2021-06-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0009_merge_0004_auto_20210603_1500_0008_order_note'),
        ('my_admin', '0009_merge_20210605_2317'),
    ]

    operations = [
    ]
