# Generated by Django 3.2.1 on 2021-06-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0011_auto_20210619_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_model', to='my_admin.product'),
        ),
    ]
