# Generated by Django 3.2.1 on 2021-06-23 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0012_alter_productmodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_admin.productmodel'),
        ),
    ]
