# Generated by Django 3.2.1 on 2021-06-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0013_orderproduct_product_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
