# Generated by Django 3.2.1 on 2021-06-24 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0014_auto_20210624_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
