# Generated by Django 3.2.1 on 2021-06-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0018_product_is_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_price',
            new_name='is_show_price',
        ),
    ]
