# Generated by Django 3.2.1 on 2021-06-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0019_rename_is_price_product_is_show_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_show_price',
            new_name='is_hide_price',
        ),
    ]
